# -*- coding: utf-8 -*-
"""Train_YoloV3 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zpo3apL3mgXJw2-gk8GR4ScAJpO_e049

**Connect google drive**
"""

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
!ln -s /content/gdrive/My\ Drive/ /mydrive

"""**1) Clone the Darknet**


"""

!git clone https://github.com/AlexeyAB/darknet
!sudo apt install libopencv-dev python3-opencv
!sudo apt install cmake

"""**2) Compile Darknet using Nvidia GPU**

"""

# Commented out IPython magic to ensure Python compatibility.
# change makefile to have GPU and OPENCV enabled
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!make

"""**3) Configure Darknet network for training YOLO V3**"""

!cp cfg/yolov3.cfg cfg/yolov3_training.cfg

!sed -i 's/batch=1/batch=64/' cfg/yolov3_training.cfg
!sed -i 's/subdivisions=1/subdivisions=16/' cfg/yolov3_training.cfg
!sed -i 's/max_batches = 500200/max_batches = 4000/' cfg/yolov3_training.cfg
!sed -i '610 s@classes=80@classes=2@' cfg/yolov3_training.cfg
!sed -i '696 s@classes=80@classes=2@' cfg/yolov3_training.cfg
!sed -i '783 s@classes=80@classes=2@' cfg/yolov3_training.cfg
!sed -i '603 s@filters=255@filters=21@' cfg/yolov3_training.cfg
!sed -i '689 s@filters=255@filters=21@' cfg/yolov3_training.cfg
!sed -i '776 s@filters=255@filters=21@' cfg/yolov3_training.cfg

# Create folder on google drive so that we can save there the weights
!mkdir "/mydrive/yolov3"

!echo -e "aashirvaad_1_kg\naashirvaad_5_kg" > data/obj.names
!echo -e 'classes=2\ntrain  = data/train.txt\nvalid  = data/test.txt\nnames = data/obj.names\nbackup = /mydrive/yolov3' > data/obj.data
!mkdir data/obj

# Download weights darknet model 53
!wget https://pjreddie.com/media/files/darknet53.conv.74

"""**4) Extract Images**

The images need to be inside a zip archive called "images.zip" and they need to be inside the folder "yolov3" on Google Drive
"""

!unzip /mydrive/yolov3/size_variance.zip -d data/obj

import glob
images_list = glob.glob("data/obj/*.jpg")
print(len(images_list))
print(images_list)

#Create training.txt file
file = open("data/train.txt", "w") 
file.write("\n".join(images_list)) 
file.close()

"""**6) Start the training**"""

# Start the training
!./darknet detector train data/obj.data cfg/yolov3_training.cfg darknet53.conv.74  -dont_show